### ISSUE TITLE
Bad line breaking

### ISSUE THREAD

**Issue by PierreLgrd** [dergachev/puppypaste#2]
If I input a big paragraph in  HTML text ( from fr.lipsum.com). Linea breaking is not the same when converted into Markdown or Textile.
![capture d ecran](https://cloud.githubusercontent.com/assets/15238779/12359086/7df2591a-bb7e-11e5-8c2a-ae08968bfc1f.png)

**Comment by dergachev** [comment]
Turns out that it's only when you COPY the text in Firefox (not Chrome), it tries to be helpful by wrapping it at around 80 chars, since in HTML \n aren't actually newlines.

The markdown converter seems to choke on this, though. It should clear them out.
